### ISSUE TITLE
Implement Article 3

### ISSUE THREAD

**Issue by bolom** [enmarche972/en-marche-martinique.fr#15]
Article 3 / Desktop
Article 3 / Mobile

**Comment by bolom** [comment]
@dev-cyprium did you see the link in Avocode?

**Comment by bolom** [comment]
missing the mobile version

**Comment by bolom** [comment]
@dev-cyprium i have update this article now i am not able to see it

**Comment by bolom** [comment]
@dev-cyprium i have update this post but i am not able to see it

**Comment by dev-cyprium** [comment]
Just open it on mobile phone or resize the window less then 700 px
I didn't create a seperate page, used @media queries, is that what you wanted?

**Comment by bolom** [comment]
I don't follow you. 

Bolo

**Comment by bolom** [comment]
@dev-cyprium could you please tell me why i don't see this article?

**Comment by dev-cyprium** [comment]
![see](https://user-images.githubusercontent.com/6002628/28381261-75ae32f8-6cba-11e7-99bd-9a0f07259f84.png)
Are you sure we're looking at the same article, this is my view of it.
Here is the link aswell: http://localhost:4000/actualites/2017/06/11/en-marche-martinique-s-organise.html

**Comment by bolom** [comment]
still don't understand why you show me. the problem is don't see the
article in the homepage

2017-07-19 13:43 GMT-04:00 Stefan Kupresak <notifications@github.com>:

**Comment by bolom** [comment]
works as excepted
