### ISSUE TITLE
 Implement the new home

### ISSUE THREAD

**Issue by bolom** [enmarche972/en-marche-martinique.fr#17]
![capture d ecran 5](https://user-images.githubusercontent.com/72155/27458411-ead23c2c-5776-11e7-8dd7-1bcdfad9932d.png)

**Comment by bolom** [comment]
@dev-cyprium not implemented

**Comment by dev-cyprium** [comment]
Implemented in #30

**Comment by bolom** [comment]
-  where is the languages drop down menu?
- where is the map?
- Where are the social buttons
- the thumbnails are two small. I have a weird white marge on the left
- weird pink button in contact form
- there is no validation. I am able to submit a message without any email or message. add HTML 5 validation.

**What we have.**

![img_9433](https://user-images.githubusercontent.com/72155/28505462-33988cac-6ff2-11e7-841d-78e8f33124bb.PNG)
![img_9434](https://user-images.githubusercontent.com/72155/28505477-5e4a2c1c-6ff2-11e7-908e-b8c720761a39.PNG)
![img_9435](https://user-images.githubusercontent.com/72155/28505494-7f34ecb4-6ff2-11e7-8a57-335a44a220d3.PNG)

Should be exactly like that

![mobile-2](https://user-images.githubusercontent.com/72155/28505525-c6cfd386-6ff2-11e7-941b-2cffc294fdf8.png)
