### ISSUE TITLE
Mobile - Text is not correctly aligned

### ISSUE THREAD

**Issue by bolom** [enmarche972/en-marche-martinique.fr#33]
**Actual Design**

<img width="326" alt="capture d ecran 2017-07-23 a 22 08 14" src="https://user-images.githubusercontent.com/72155/28505767-ac928ffc-6ff4-11e7-9c72-50b62fe5f923.PNG">

**What we should have**
<img width="326" alt="capture d ecran 2017-07-23 a 22 08 14" src="https://user-images.githubusercontent.com/72155/28505770-b0039afa-6ff4-11e7-8bf8-32f18bdebae9.png">

**Comment by dev-cyprium** [comment]
![better](https://user-images.githubusercontent.com/6002628/28537607-c7a320ec-70ab-11e7-9dd1-8e47b4e93f82.png)
Is this better?

**Comment by bolom** [comment]
Yes

Le lun. 24 juil. 2017 à 14:08, Stefan Kupresak <notifications@github.com> a
écrit :
