### ISSUE TITLE
Image is blurry 

### ISSUE THREAD

**Issue by bolom** [enmarche972/en-marche-martinique.fr#34]
![img_9437](https://user-images.githubusercontent.com/72155/28505828-0154e148-6ff5-11e7-97cf-3555700113d8.PNG)

- image is blurry
- the text should not included in image

**Comment by dev-cyprium** [comment]
Is there a .svg map without text that I can use for this?

**Comment by bolom** [comment]
I don't think so. It's complicate to remove the text ?
Le lun. 24 juil. 2017 à 14:22, Stefan Kupresak <notifications@github.com> a
écrit :
